set(SOURCE_FILES
sources/glfw/GLFWEncapsulation.cpp
sources/glfw/GLFWEncapsulation.h
sources/imgui/ConsoleLogs.cpp
sources/imgui/ConsoleLogs.h
sources/imgui/EditorUI.cpp
sources/imgui/EditorUI.h
sources/imgui/GameViewport.cpp
sources/imgui/GameViewport.h
sources/imgui/ImguiImpl.cpp
sources/imgui/ImguiImpl.h
sources/imgui/UI.cpp
sources/imgui/UI.h
sources/imgui/UIDebugBenchmarkValue.cpp
sources/imgui/UIDebugBenchmarkValue.h
sources/imgui/UIDebugSection.cpp
sources/imgui/UIDebugSection.h
sources/imgui/UIDebugWindow.cpp
sources/imgui/UIDebugWindow.h
sources/imgui/UIFont.cpp
sources/imgui/UIFont.h
sources/imgui/UIObject.cpp
sources/imgui/UIObject.h
sources/imgui/UITheme.cpp
sources/imgui/UITheme.h
sources/render/Camera/CameraComponent.cpp
sources/render/Camera/CameraComponent.h
sources/render/Camera/FreeCam.cpp
sources/render/Camera/FreeCam.h
sources/render/EngineWindow/EngineWindow.cpp
sources/render/EngineWindow/EngineWindow.h
sources/render/Image/Image.cpp
sources/render/Image/Image.h
sources/render/Light/LightComponent.cpp
sources/render/Light/LightComponent.h
sources/render/Material/Material.cpp
sources/render/Material/Material.h
sources/render/RenderComponent/ModelComponent.cpp
sources/render/RenderComponent/ModelComponent.h
sources/render/RenderInclude.cpp
sources/render/RenderInclude.h
sources/render/Shaders/ShaderModule.cpp
sources/render/Shaders/ShaderModule.h
sources/render/TextureImage/VulkanTextureImage.cpp
sources/render/TextureImage/VulkanTextureImage.h
sources/render/Vertex/PhysicsDebugVertex.h
sources/render/Vertex/Vertex.h
sources/render/VulkanBuffer/VulkanBuffer.cpp
sources/render/VulkanBuffer/VulkanBuffer.h
sources/render/VulkanBuffer/VulkanIndexBuffer.cpp
sources/render/VulkanBuffer/VulkanIndexBuffer.h
sources/render/VulkanBuffer/VulkanVertexBuffer.cpp
sources/render/VulkanBuffer/VulkanVertexBuffer.h
sources/render/VulkanCommandPool/VulkanCommandPool.cpp
sources/render/VulkanCommandPool/VulkanCommandPool.h
sources/render/VulkanConstants.h
sources/render/VulkanDebugMessenger/VulkanDebugMessenger.cpp
sources/render/VulkanDebugMessenger/VulkanDebugMessenger.h
sources/render/VulkanDescriptor/VulkanDescriptor.cpp
sources/render/VulkanDescriptor/VulkanDescriptor.h
sources/render/VulkanDescriptor/VulkanDescriptorPool.cpp
sources/render/VulkanDescriptor/VulkanDescriptorPool.h
sources/render/VulkanDescriptor/VulkanDescriptorSet.cpp
sources/render/VulkanDescriptor/VulkanDescriptorSet.h
sources/render/VulkanDescriptor/VulkanDescriptorSetLayout.cpp
sources/render/VulkanDescriptor/VulkanDescriptorSetLayout.h
sources/render/VulkanDevice/VulkanDevice.cpp
sources/render/VulkanDevice/VulkanDevice.h
sources/render/VulkanDevice/VulkanDeviceList.cpp
sources/render/VulkanDevice/VulkanDeviceList.h
sources/render/VulkanFramebuffer/VulkanFramebuffer.cpp
sources/render/VulkanFramebuffer/VulkanFramebuffer.h
sources/render/VulkanGlfwApplication/VulkanGlfwApplication.cpp
sources/render/VulkanGlfwApplication/VulkanGlfwApplication.h
sources/render/VulkanInstance/VulkanInstance.cpp
sources/render/VulkanInstance/VulkanInstance.h
sources/render/VulkanMacros.h
sources/render/VulkanPipeline/VulkanPipeline.cpp
sources/render/VulkanPipeline/VulkanPipeline.h
sources/render/VulkanPushConstant/VulkanPushConstant.cpp
sources/render/VulkanPushConstant/VulkanPushConstant.h
sources/render/VulkanQueryPool/VulkanQueryPool.cpp
sources/render/VulkanQueryPool/VulkanQueryPool.h
sources/render/VulkanRenderer/VulkanRenderer.cpp
sources/render/VulkanRenderer/VulkanRenderer.h
sources/render/VulkanRenderPass/VulkanRenderPass.cpp
sources/render/VulkanRenderPass/VulkanRenderPass.h
sources/render/VulkanRHI/VulkanRHI.cpp
sources/render/VulkanRHI/VulkanRHI.h
sources/render/VulkanSwapchain/VulkanSwapchain.cpp
sources/render/VulkanSwapchain/VulkanSwapchain.h
sources/render/VulkanSwapchain/VulkanSwapchainFrame.cpp
sources/render/VulkanSwapchain/VulkanSwapchainFrame.h
sources/render/VulkanTextureSampler/VulkanTextureSampler.cpp
sources/render/VulkanTextureSampler/VulkanTextureSampler.h
sources/render/VulkanUniformBuffer/VulkanLightBuffers.cpp
sources/render/VulkanUniformBuffer/VulkanLightBuffers.h
sources/render/VulkanUniformBuffer/VulkanUniformBuffer.cpp
sources/render/VulkanUniformBuffer/VulkanUniformBuffer.h
sources/render/VulkanUtils.hpp
sources/shaders/depth.vert
sources/shaders/physicsDebug.frag
sources/shaders/physicsDebug.vert
sources/shaders/shader.frag
sources/shaders/shader.vert
sources/shaders/skybox.frag
sources/shaders/skybox.vert )
