set(SOURCE_FILES
sources/editor/GameComponents/BoulderComponent.cpp
sources/editor/GameComponents/BoulderComponent.h
sources/editor/GameComponents/CarChassisComponent.h
sources/editor/GameComponents/CarControllerComponent.cpp
sources/editor/GameComponents/CarControllerComponent.h
sources/editor/GameComponents/CarWheelComponent.h
sources/editor/GameComponents/CheckpointComponent.cpp
sources/editor/GameComponents/CheckpointComponent.h
sources/editor/GameComponents/HUDComponent.cpp
sources/editor/GameComponents/HUDComponent.h
sources/editor/GameComponents/PlatformComponent.cpp
sources/editor/GameComponents/PlatformComponent.h
sources/editor/GameComponents/PlatformSpawner.cpp
sources/editor/GameComponents/PlatformSpawner.h
sources/editor/GameComponents/RotationLimiterComponent.cpp
sources/editor/GameComponents/RotationLimiterComponent.h
sources/editor/GameEntities/Boulder.cpp
sources/editor/GameEntities/Boulder.h
sources/editor/GameEntities/Car.cpp
sources/editor/GameEntities/Car.h
sources/editor/GameEntities/Checkpoint.cpp
sources/editor/GameEntities/Checkpoint.h
sources/editor/GameEntities/Platform.cpp
sources/editor/GameEntities/Platform.h
sources/editor/main.cpp
sources/editor/SceneTemplate.cpp
sources/editor/SceneTemplate.h
 )
