set(SOURCE_FILES
sources/core/Array.h
sources/core/ArrayView.cpp
sources/core/ArrayView.doc.h
sources/core/CLog.cpp
sources/core/CLog.doc.h
sources/core/CLog.h
sources/core/Constant.h
sources/core/DebugWindow/BenchmarkValue.cpp
sources/core/DebugWindow/BenchmarkValue.h
sources/core/DebugWindow/DebugSection.cpp
sources/core/DebugWindow/DebugSection.h
sources/core/DebugWindow/DebugWatchValue.cpp
sources/core/DebugWindow/DebugWatchValue.h
sources/core/DebugWindow/DebugWindow.cpp
sources/core/DebugWindow/DebugWindow.h
sources/core/Delegate.h
sources/core/ECS/Component.h
sources/core/ECS/Entity.cpp
sources/core/ECS/Entity.h
sources/core/ECS/EntityDetail.h
sources/core/ECS/Event.cpp
sources/core/ECS/Event.h
sources/core/ECS/Handle.h
sources/core/ECS/HasFunction.h
sources/core/ECS/Macro.h
sources/core/ECS/System.h
sources/core/ECS/template/CompTemplate.h
sources/core/ECS/World.cpp
sources/core/ECS/World.h
sources/core/File.cpp
sources/core/File.h
sources/core/filesys/Config.cpp
sources/core/filesys/Config.doc.h
sources/core/filesys/Config.h
sources/core/filesys/ErrorManager.h
sources/core/filesys/MemoryMappedFile.cpp
sources/core/filesys/MemoryMappedFile.doc.h
sources/core/filesys/MemoryMappedFile.h
sources/core/Flag.h
sources/core/GameLoop.cpp
sources/core/GameLoop.h
sources/core/InputManager/DefaultInputManager.cpp
sources/core/InputManager/DefaultInputManager.h
sources/core/InputManager/InputManager.doc.h
sources/core/InputManager/InputManager.h
sources/core/InputManager/InputManager.inl
sources/core/PoolAllocator.cpp
sources/core/PoolAllocator.doc.h
sources/core/PoolAllocator.h
sources/core/PoolAllocator.inl
sources/core/reflection/BlackMagic.h
sources/core/reflection/EnumMeta.cpp
sources/core/reflection/EnumMeta.h
sources/core/reflection/FuncMeta.cpp
sources/core/reflection/FuncMeta.h
sources/core/reflection/FuncPtrMeta.h
sources/core/reflection/Primitive.h
sources/core/reflection/ReflectionAPI.cpp
sources/core/reflection/ReflectionAPI.h
sources/core/reflection/StructMeta.cpp
sources/core/reflection/StructMeta.h
sources/core/reflection/StructureField.cpp
sources/core/reflection/StructureField.h
sources/core/reflection/template/EEnumTemplate.cpp
sources/core/reflection/template/EEnumTemplate.h
sources/core/reflection/template/NonRegressionTest.cpp
sources/core/reflection/template/NonRegressionTest.h
sources/core/reflection/template/StructTemplate.cpp
sources/core/reflection/template/StructTemplate.h
sources/core/reflection/Wrapper.h
sources/core/ResourceManager.cpp
sources/core/ResourceManager.doc.h
sources/core/ResourceManager.h
sources/core/ResourceManager.inl
sources/core/scenegraph/SceneGraph.cpp
sources/core/scenegraph/SceneGraph.h
sources/core/scenegraph/SceneNode.cpp
sources/core/scenegraph/SceneNode.h
sources/core/scenegraph/Transform.cpp
sources/core/scenegraph/Transform.h
sources/core/ThreadPool.cpp
sources/core/ThreadPool.doc.h
sources/core/ThreadPool.h
sources/core/ThreadPool.inl
sources/core/TimerManager.cpp
sources/core/TimerManager.h )
